# LCM
package:
    name: lcm
    version: 1.3.1

source:
    git_url: https://github.com/lcm-proj/lcm.git
    git_branch: master
    # git_tag: v1.3.1
  
build:
    number: 0

requirements:
    build:
        - cmake
        - numpy
        - mkl
        - python
        - zlib
    run:
        - python
        - numpy
        - mkl
        - zlib

about:
    home: https://github.com/lcm-proj/lcm
    license: GNU LGPL-2.1
