# LCM
package:
    name: lcm

source:
    git_url: https://github.com/lcm-proj/lcm.git
    git_branch: master
  
requirements:
    build:
        - cmake
        - numpy
        - mkl
        - python
        - zlib
    run:
        - python
        - numpy
        - mkl
        - zlib

about:
    home: https://github.com/lcm-proj/lcm
    license: GNU LGPL-2.1
