package:
  name: libnabo
  version: 1.0.6

source:
  git_url: https://github.com/ethz-asl/libnabo.git
  git_rev: 1.0.6

requirements:
  build:
    - cmake
    - eigen
    - boost
  run:

about:
  home: https://github.com/ethz-asl/libnabo
  license: LGPL-3.0 
  summary: A fast K Nearest Neighbor library for low-dimensional spaces 
