# libbot
package:
    name: libbot
    version: 2

source:
    git_url: https://github.com/RobotLocomotion/libbot.git
    git_branch: master
  
requirements:
    build:
        - cmake
        - numpy
        - python
        - lcm
    run:
        - python
        - numpy
        - lcm

about:
    home: https://github.com/RobotLocomotion/libbot.git
    license: GNU LGPL-3.0
